### ISSUE TITLE
Use market://-link for app when page is opened from Android device

### ISSUE THREAD

**Issue by ntninja** [Neamar/kisslauncher.com#2]
Currently the `http://kisslauncher.com/` page always links to `https://play.google.com/store/apps/details?id=fr.neamar.kiss`.

While this certainly made sense in the past, nowadays _KISS Launcher_ is also (at least) available on F-Droid. In order to simplify installation for F-Droid users I'd be nice if the website could detect if its being displayed on an Android device and, in this case, change the `href` of all `https://play.google.com/store/apps/details?id=fr.neamar.kiss`-links to `market://details?id=fr.neamar.kiss`.

Pros:
- Google Play installation will still work
- Users that have other stores installed will be able to choose which store to install _KISS Launcher_ from
- Users that do not have the Google Play store will be able to choose to install _KISS Launcher_ from another store

Cons:
- None that I can see

If you agree with me I'll be glad to send you a patch. :-)

**Comment by Neamar** [comment]
I'm in!
